# Generated by Django 3.2.25 on 2024-12-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
